import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {openJobStore} from '../lib/job-store.mjs';import {Scheduler} from '../lib/scheduler.mjs';import {mountJobsApi} from '../lib/jobs-api.mjs';
test('HTTP jobs: duplicate retry snapshot origin cancellation and details',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'api-jobs-'));const store=openJobStore({path:join(dir,'db')});const scheduler=new Scheduler({store});let label='initial';const app=express();app.use(express.json());mountJobsApi(app,{store,scheduler,buildBrief:async input=>({profile:{id:'fixture',label},session:{instructions:input.instructions,audio:{output:{voice:input.voice}}}}),allowedOrigins:new Set(['http://localhost'])});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>{server.close();store.close();rmSync(dir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`;
 const body={to:'test:sim1',when:'now',instructions:'hello',voice:'alloy'};const post=(payload,key='same',origin)=>fetch(base+'/api/jobs',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key,...(origin?{Origin:origin}:{})},body:JSON.stringify(payload)});
 let res=await post(body);assert.equal(res.status,201);const job=await res.json();label='changed';await new Promise(r=>setTimeout(r,10));res=await post(body);assert.equal(res.status,200);assert.equal((await res.json()).id,job.id);assert.equal(store.getJob(job.id).brief.profile.label,'initial');assert.equal((await post({...body,to:'12345678900'})).status,409);
 assert.equal((await post(body,'blocked','https://evil.example')).status,403);assert.equal((await post({...body,maxDurationSeconds:1},'invalid')).status,400);
 const listed=await (await fetch(base+'/api/jobs')).json();assert.equal(listed.jobs.length,1);assert.equal(listed.jobs[0].brief,undefined);
 assert.equal((await fetch(base+'/api/jobs/'+job.id,{method:'DELETE'})).status,200);assert.equal(store.getJob(job.id).state,'cancelled');
 const c=await (await fetch(base+'/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:'test:sim1',name:'Test'})})).json();assert.equal((await fetch(base+'/api/contacts/'+c.id,{method:'DELETE'})).status,200);
});
