import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {WebSocketServer} from 'ws';import OpenAI from 'openai';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {openJobStore} from '../lib/job-store.mjs';import {CallHub} from '../lib/calls.mjs';import {Scheduler} from '../lib/scheduler.mjs';
const wait=async check=>{for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,10));}throw Error('fixture lifecycle timeout');};
test('real mock bridge/Live lifecycle persists transcript and final usage',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'full-lifecycle-'));const bridge=new WebSocketServer({port:0}),live=new WebSocketServer({port:0});await Promise.all([once(bridge,'listening'),once(live,'listening')]);let commands=0,pbxPeer,livePeer;
 bridge.on('connection',ws=>{pbxPeer=ws;ws.send(JSON.stringify({type:'hello',calls:[]}));ws.on('message',(d,binary)=>{if(binary)return;const msg=JSON.parse(d);if(msg.type==='call.start'){commands++;ws.send(JSON.stringify({type:'call.state',slot:msg.slot,id:'pbx-fixture',state:'answered'}));}if(msg.type==='call.hangup')ws.send(JSON.stringify({type:'call.state',slot:msg.slot,state:'ended',reason:'Normal Clearing'}));});});
 live.on('connection',ws=>{livePeer=ws;ws.on('message',d=>{const msg=JSON.parse(d);if(msg.type==='session.start'){ws.send(JSON.stringify({type:'session.started',session:{id:'mock-live'}}));ws.send(JSON.stringify({type:'session.input_transcript.delta',delta:'Здравствуйте',start_ms:0,end_ms:100}));ws.send(JSON.stringify({type:'session.output_transcript.delta',delta:'Добрый день',start_ms:101,end_ms:200}));}if(msg.type==='session.close')ws.send(JSON.stringify({type:'session.closed',usage:{seconds:12}}));});});
 const store=openJobStore({path:join(dir,'db')}),hub=new CallHub({url:`ws://127.0.0.1:${bridge.address().port}`,token:'test',openai:new OpenAI({apiKey:'test',baseURL:`http://127.0.0.1:${live.address().port}/v1`})});const scheduler=new Scheduler({store,hub});
 t.after(()=>{scheduler.stop();hub.close();store.close();for(const ws of [...bridge.clients,...live.clients])ws.terminate();bridge.close();live.close();rmSync(dir,{recursive:true,force:true});});
 await wait(()=>hub.availability().ready);
 const job=store.createJob({to:'test:sim1',name:'Mock',scheduledAt:new Date().toISOString(),brief:{profile:{id:'mock',label:'Mock'},session:{model:'gpt-live-1',audio:{output:{voice:'alloy'}}}},maxDurationSeconds:30},'full');scheduler.tick();await wait(()=>store.getJob(job.id).result?.transcript?.length===2);hub.byId(store.getJob(job.id).callId).hangup();await wait(()=>store.getJob(job.id).state==='completed');
 const result=store.getJob(job.id).result;assert.equal(result.cleanupConfirmed,true);assert.equal(result.usage.seconds,12);assert.equal(result.transcript[0].text,'Здравствуйте');scheduler.tick();assert.equal(commands,1);assert.equal(hub.availability().busy,false);assert.equal(typeof hub.close,'function');
});
