import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {once} from 'node:events';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {WebSocketServer} from 'ws';import {openJobStore} from '../lib/job-store.mjs';import {Scheduler} from '../lib/scheduler.mjs';
test('SIGKILL after bridge command cannot cause a second attempt on restart',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'crash-call-')),path=join(dir,'db');const pbx=new WebSocketServer({port:0}),live=new WebSocketServer({port:0});await Promise.all([once(pbx,'listening'),once(live,'listening')]);let attempts=0;let sent;
 const commanded=new Promise(resolve=>sent=resolve);pbx.on('connection',ws=>{ws.send(JSON.stringify({type:'hello',calls:[]}));ws.on('message',d=>{if(JSON.parse(d).type==='call.start'){attempts++;sent();}});});
 const code=`import {openJobStore} from './lib/job-store.mjs';import {Scheduler} from './lib/scheduler.mjs';import {CallHub} from './lib/calls.mjs';import OpenAI from 'openai';const store=openJobStore({path:process.argv[1]});store.createJob({to:'test:sim1',scheduledAt:new Date().toISOString(),brief:{profile:{id:'mock',label:'Mock'},session:{model:'gpt-live-1'}},maxDurationSeconds:30},'crash');const hub=new CallHub({url:process.argv[2],token:'test',openai:new OpenAI({apiKey:'test',baseURL:process.argv[3]})});new Scheduler({store,hub}).start();`;
 const child=spawn(process.execPath,['--input-type=module','-e',code,path,`ws://127.0.0.1:${pbx.address().port}`,`http://127.0.0.1:${live.address().port}/v1`],{stdio:'ignore'});
 let store;t.after(()=>{child.kill('SIGKILL');store?.close();for(const s of [...pbx.clients,...live.clients])s.terminate();pbx.close();live.close();rmSync(dir,{recursive:true,force:true});});
 await Promise.race([commanded,new Promise((_,reject)=>{const timeout=setTimeout(()=>reject(Error('no command')),3000);timeout.unref();})]);const exited=once(child,'exit');child.kill('SIGKILL');await exited;
 store=openJobStore({path});store.recover(Date.now());const job=store.listJobs()[0];assert.equal(job.state,'unknown');const scheduler=new Scheduler({store,hub:{availability:()=>({ready:true,busy:false}),start(){attempts++;throw Error('unexpected retry');}}});scheduler.tick();assert.equal(attempts,1);
});
