import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {openJobStore} from '../lib/job-store.mjs';import {Scheduler} from '../lib/scheduler.mjs';
function setup(t){let now=1000000;const dir=mkdtempSync(join(tmpdir(),'scheduler-'));const path=join(dir,'db');const store=openJobStore({path,clock:()=>now});let busy=false;let attempts=0;let call;const hub={availability:()=>({ready:true,busy,reason:'занято'}),start(){attempts++;busy=true;call=Object.assign(new EventEmitter(),{id:'call',result:()=>({cleanupConfirmed:true,pbxEnded:true,liveClosed:true,answeredAt:now,transcript:[{text:'Тест'}],usage:{seconds:2}}),hangup(){}});return call;}};const scheduler=new Scheduler({store,hub,clock:()=>now});t.after(()=>{scheduler.stop();store.close();rmSync(dir,{recursive:true,force:true});});return {store,hub,scheduler,get attempts(){return attempts;},get call(){return call;},time:n=>now=n,busy:v=>busy=v,path};}
const input={to:'test:sim1',scheduledAt:new Date(1000000).toISOString(),brief:{session:{},profile:{id:'test',label:'Тест'}},maxDurationSeconds:300};
test('one attempt and persisted result without a browser',t=>{const f=setup(t);const j=f.store.createJob(input,'a');f.scheduler.tick();f.scheduler.tick();assert.equal(f.attempts,1);assert.equal(f.store.getJob(j.id).state,'active');f.call.emit('closed');assert.equal(f.store.getJob(j.id).state,'completed');assert.equal(f.store.getJob(j.id).result.usage.seconds,2);f.scheduler.tick();assert.equal(f.attempts,1);});
test('busy waits then expires and cancel wins before claim',t=>{const f=setup(t);const j=f.store.createJob(input,'a');f.busy(true);f.scheduler.tick();assert.equal(f.store.getJob(j.id).state,'waiting');f.time(1120001);f.scheduler.tick();assert.equal(f.store.getJob(j.id).state,'missed');assert.equal(f.attempts,0);const c=f.store.createJob({...input,scheduledAt:new Date(1120001).toISOString()},'b');f.store.cancel(c.id);f.busy(false);f.scheduler.tick();assert.equal(f.attempts,0);});
test('exception after claim never retries',t=>{const f=setup(t);f.hub.start=()=>{throw Error('unknown send outcome');};const j=f.store.createJob(input,'a');f.scheduler.tick();assert.equal(f.store.getJob(j.id).state,'unknown');f.scheduler.tick();assert.equal(f.store.getJob(j.id).state,'unknown');});
test('claim persisted before send and recovery never repeats',t=>{const f=setup(t);const j=f.store.createJob(input,'a');f.store.claim(j.id,1000000);f.store.recover(1000000);f.scheduler.tick();assert.equal(f.attempts,0);assert.equal(f.store.getJob(j.id).state,'unknown');});
test('unconfirmed cleanup produces unknown',t=>{const f=setup(t);const j=f.store.createJob(input,'a');f.scheduler.tick();f.call.result=()=>({cleanupConfirmed:false});f.call.emit('closed');assert.equal(f.store.getJob(j.id).state,'unknown');});
test('storage failure during active event stops launches and hangs up',t=>{const f=setup(t);const j=f.store.createJob(input,'a');f.scheduler.tick();let hangs=0;f.call.hangup=()=>hangs++;f.store.updateAttempt=()=>{throw Error('disk full');};f.call.emit('event',{type:'session.input_transcript.delta'});assert.ok(f.scheduler.failed);assert.equal(hangs,1);f.scheduler.tick();assert.equal(f.attempts,1);});
test('operator stop remains visible until confirmed lifecycle result',t=>{const f=setup(t);const j=f.store.createJob(input,'a');f.scheduler.tick();f.scheduler.stopJob(j.id);assert.equal(f.store.getJob(j.id).stopping,true);assert.equal(f.store.getJob(j.id).state,'active');});
